name: Auto-Create-Parser-Issues

on:
  issues:
    types: [opened, edited]

jobs:
  createIssues:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.issue.title, 'パーサー追加') && contains(github.event.issue.labels.*.name, 'Epic') && contains(github.event.issue.labels.*.name, 'PARSER') }}
    steps:
      # - name: print event
      #   run: |
      #     echo ${{ toJson(github.event.issue) }}

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - run: |
          SERVICE_NAME=$(echo "${{ github.event.issue.title }}" | sed 's/パーサー追加(\(.*\))/\1/')
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
      
      - name: Create issue
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVICE_NAME: ${{ env.SERVICE_NAME }}
        with:
          filename: .github/create_parser_issue_template/test_template.md

      - name: Create issue
        id: create-issue2
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVICE_NAME: ${{ env.SERVICE_NAME }}2
        with:
          filename: .github/create_parser_issue_template/test_template2.md
      
      # - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      # - run: 'echo Created ${{ steps.create-issue.outputs.url }}'

      - name: Test steps array
        run: |
          for number in ${{ join(steps.*.outputs.number, ",") }}
          do
            echo "number: ${number}"
          done